#!/usr/bin/perl
use warnings;

my %SampleIndex;
$index1='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG';
$index2='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG';
$index3='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG';
$index4='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG';
$index5='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG';
$index6='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG';
$index7='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG';
$index8='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG';
$index9='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG';
$index10='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG';
$index11='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG';
$index12='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG';
$index13='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTCAACAATCTCGTATGCCGTCTTCTGCTTG';
$index14='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACAGTTCCGTATCTCGTATGCCGTCTTCTGCTTG';
$index15='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATGTCAGAATCTCGTATGCCGTCTTCTGCTTG';
$index16='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCCGTCCATCTCGTATGCCGTCTTCTGCTTG';
$index18='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTCCGCACATCTCGTATGCCGTCTTCTGCTTG';
$index19='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGAAACGATCTCGTATGCCGTCTTCTGCTTG';
$index20='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTGGCCTTATCTCGTATGCCGTCTTCTGCTTG';
$index21='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGTTTCGGAATCTCGTATGCCGTCTTCTGCTTG';
$index22='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGTACGTAATCTCGTATGCCGTCTTCTGCTTG';
$index23='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACGAGTGGATATCTCGTATGCCGTCTTCTGCTTG';
$index25='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACACTGATATATCTCGTATGCCGTCTTCTGCTTG';
$index27='AGATCGGAAGAGCACACGTCTGAACTCCAGTCACATTCCTTTATCTCGTATGCCGTCTTCTGCTTG';
$primer5='AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT';
$SR_primer='GATCGTCGGACTGTAGAACTCTGAACGTGTAGATCTCGGTGGTCGCCGTATCATT'; 
$SampleIndex{'col0-1'}=$index3;
$SampleIndex{'col0-2'}=$index4;
$SampleIndex{'ect2-3-4-1'}=$index7;
$SampleIndex{'ect2-3-4-2'}=$index8;
$SampleIndex{'Y3M-1'}=$index5;
$SampleIndex{'Y3M-2'}=$index6;

@Sample=(keys %SampleIndex);

foreach(@Sample){
   system("cutadapt -a $SampleIndex{$_} -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT -o $_.trimmed.R1.fq.gz -p $_.trimmed.R2.fq.gz $_.combined_R1.fastq.gz $_.combined_R2.fastq.gz");
}


foreach(@Sample){
   system(
       "hisat2 -p 30 -x /home/l/backup1/refgenome/Arabidopsis/hisat2/Arabidopsis_tran -1 $_.trimmed.R1.fq.gz -2 $_.trimmed.R2.fq.gz -S $_.sam
        samtools view -bS $_.sam > $_.bam
        samtools sort -o $_.sorted.bam $_.bam
        samtools index $_.sorted.bam
        rm -rf $_.sam
        rm -rf $_.bam"
   );
}

foreach(@Sample){
    system(
    	"echo $_ >> mapping_report.txt
    	 samtools flagstat $_.sorted.bam >> mapping_report.txt"
    );
}




